# Generated by Django 4.2.1 on 2023-08-03 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoce_no',
            new_name='invoice_no',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cust_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('quant', models.IntegerField(max_length=100)),
                ('unit_price', models.FloatField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.invoice')),
            ],
        ),
    ]
